import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by Mangogi",
};

export default function RegisterPage() {
  return (
    <div>
      <h1>reg</h1>
    </div>
  );
}
