import { Metadata } from "next";
import Register from "@/app/components/utility/registeration";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by Mangogi",
};

export default function RegisterPage() {
  return <Register />;
}
